### ISSUE TITLE
`useIsomorphicLayoutEffect` not in the repo

### ISSUE THREAD

**Issue by dominikwilkowski** [Zneider/react-html-comment#10]
Hey there,

Was trying to use this component but was able to locate `useIsomorphicLayoutEffect` for this line:
https://github.com/Zneider/react-html-comment/blob/master/src/components/HTMLComment.jsx#L2

**Comment by Zneider** [comment]
@dominikwilkowski Hey there. I somehow forgot to push the files - Should be there now
